name: $(Date:dd-MM-yyyy)$(Rev:.r)
trigger:
- master
- develop
- qa
pr:
- master
- develop
- qa

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar_maerskdev_net'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'java-build-sample'
    cliProjectName: 'java-build-sample'
    cliProjectVersion: '0.0.1-SNAPSHOT'

- script: |
    ./mvnw -B -e clean sonar:sonar package 
  displayName: 'Maven Package'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
      
- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: drop

